inventorio:
  server: https://api.inventorio.cloud
  configFile: .inventorio/config.yml

commands:
  reboot:
    name: Reboot the server
    command: reboot
  inventorio-collect:
    name: Collect server status via inventorio agent
    command: inventorio collect
